// src/lib/shiki-lang-transformer.ts (备选方案)
import type { ShikiTransformer } from '@shikijs/types';
import type { Element } from 'hast';


const DISPLAY_NAMES: Record<string, string> = {
  // ========== 基础编程语言 ==========
  abap: 'ABAP',
  actionscript: 'ActionScript',
  'actionscript-3': 'ActionScript 3',
  ada: 'Ada',
  'angular-html': 'Angular HTML',
  'angular-ts': 'Angular TypeScript',
  apache: 'Apache Conf',
  apex: 'Apex',
  apl: 'APL',
  applescript: 'AppleScript',
  ara: 'Ara',
  asciidoc: 'AsciiDoc',
  adoc: 'AsciiDoc',
  asm: 'Assembly',
  astro: 'Astro',
  awk: 'AWK',
  ballierina: 'Ballerina',
  bat: 'Batch File',
  batch: 'Batch File',
  beancount: 'Beancount',
  berry: 'Berry',
  be: 'Berry',
  bibtex: 'BibTeX',
  bicep: 'Bicep',
  blade: 'Blade',
  bsl: '1C (Enterprise)',
  '1c': '1C (Enterprise)',
  c: 'C',
  c3: 'C3',
  cadence: 'Cadence',
  cdc: 'Cadence',
  cairo: 'Cairo',
  clarity: 'Clarity',
  clojure: 'Clojure',
  clj: 'Clojure',
  cmake: 'CMake',
  cobol: 'COBOL',
  codeowners: 'CODEOWNERS',
  codeql: 'CodeQL',
  ql: 'CodeQL',
  coffee: 'CoffeeScript',
  coffeescript: 'CoffeeScript',
  'common-lisp': 'Common Lisp',
  lisp: 'Common Lisp',
  coq: 'Coq',
  cpp: 'C++',
  'c++': 'C++',
  crystal: 'Crystal',
  csharp: 'C#',
  'c#': 'C#',
  cs: 'C#',
  css: 'CSS',
  csv: 'CSV',
  cue: 'CUE',
  cypher: 'Cypher',
  cql: 'Cypher',
  d: 'D',
  dart: 'Dart',
  dax: 'DAX',
  desktop: 'Desktop',
  diff: 'Diff',
  docker: 'Dockerfile',
  dockerfile: 'Dockerfile',
  dotenv: 'dotEnv',
  'dream-maker': 'Dream Maker',
  edge: 'Edge',
  elixir: 'Elixir',
  elm: 'Elm',
  'emacs-lisp': 'Emacs Lisp',
  elisp: 'Emacs Lisp',
  erb: 'ERB',
  erlang: 'Erlang',
  erl: 'Erlang',
  fennel: 'Fennel',
  fish: 'Fish',
  fluent: 'Fluent',
  ftl: 'Fluent',
  'fortran-fixed-form': 'Fortran (Fixed Form)',
  ffor: 'Fortran (Fixed Form)',
  f77: 'Fortran (Fixed Form)',
  'fortran-free-form': 'Fortran (Free Form)',
  f90: 'Fortran (Free Form)',
  f95: 'Fortran (Free Form)',
  f03: 'Fortran (Free Form)',
  f08: 'Fortran (Free Form)',
  f18: 'Fortran (Free Form)',
  fsharp: 'F#',
  'f#': 'F#',
  fs: 'F#',
  gdresource: 'GDResource',
  tscn: 'GDResource',
  tres: 'GDResource',
  gdscript: 'GDScript',
  gd: 'GDScript',
  gdshader: 'GDShader',
  genie: 'Genie',
  gherkin: 'Gherkin',
  'git-commit': 'Git Commit Message',
  'git-rebase': 'Git Rebase Message',
  gleam: 'Gleam',
  'glimmer-js': 'Glimmer JS',
  gjs: 'Glimmer JS',
  'glimmer-ts': 'Glimmer TS',
  gts: 'Glimmer TS',
  glsl: 'GLSL',
  gn: 'GN',
  gnuplot: 'Gnuplot',
  go: 'Go',
  graphql: 'GraphQL',
  gql: 'GraphQL',
  groovy: 'Groovy',
  hack: 'Hack',
  haml: 'Ruby Haml',
  handlebars: 'Handlebars',
  hbs: 'Handlebars',
  haskell: 'Haskell',
  hs: 'Haskell',
  haxe: 'Haxe',
  hcl: 'HashiCorp HCL',
  hjson: 'Hjson',
  hlsl: 'HLSL',
  html: 'HTML',
  'html-derivative': 'HTML (Derivative)',
  http: 'HTTP',
  hurl: 'Hurl',
  hxml: 'HXML',
  hy: 'Hy',
  imba: 'Imba',
  ini: 'INI',
  properties: 'INI',
  java: 'Java',
  javascript: 'JavaScript',
  js: 'JavaScript',
  cjs: 'JavaScript',
  mjs: 'JavaScript',
  jinja: 'Jinja',
  jison: 'Jison',
  json: 'JSON',
  json5: 'JSON5',
  jsonc: 'JSON with Comments',
  jsonl: 'JSON Lines',
  jsonnet: 'Jsonnet',
  jssm: 'JSSM',
  fsl: 'JSSM',
  jsx: 'JSX',
  julia: 'Julia',
  jl: 'Julia',
  kdl: 'KDL',
  kotlin: 'Kotlin',
  kt: 'Kotlin',
  kts: 'Kotlin',
  kusto: 'Kusto',
  kql: 'Kusto',
  latex: 'LaTeX',
  lean: 'Lean 4',
  lean4: 'Lean 4',
  less: 'Less',
  liquid: 'Liquid',
  llvm: 'LLVM IR',
  log: 'Log file',
  logo: 'Logo',
  lua: 'Lua',
  luau: 'Luau',
  make: 'Makefile',
  makefile: 'Makefile',
  markdown: 'Markdown',
  md: 'Markdown',
  marko: 'Marko',
  matlab: 'MATLAB',
  mdc: 'MDC',
  mdx: 'MDX',
  mermaid: 'Mermaid',
  mmd: 'Mermaid',
  mipsasm: 'MIPS Assembly',
  mips: 'MIPS Assembly',
  mojo: 'Mojo',
  moonbit: 'MoonBit',
  mbt: 'MoonBit',
  mbti: 'MoonBit',
  move: 'Move',
  narrat: 'Narrat Language',
  nar: 'Narrat Language',
  nextflow: 'Nextflow',
  nf: 'Nextflow',
  nginx: 'Nginx',
  nim: 'Nim',
  nix: 'Nix',
  nushell: 'nushell',
  nu: 'nushell',
  'objective-c': 'Objective-C',
  objc: 'Objective-C',
  'objective-cpp': 'Objective-C++',
  ocaml: 'OCaml',
  odin: 'Odin',
  openscad: 'OpenSCAD',
  scad: 'OpenSCAD',
  pascal: 'Pascal',
  perl: 'Perl',
  php: 'PHP',
  pkl: 'Pkl',
  plsql: 'PL/SQL',
  po: 'Gettext PO',
  pot: 'Gettext PO',
  potx: 'Gettext PO',
  polar: 'Polar',
  postcss: 'PostCSS',
  powerquery: 'PowerQuery',
  powershell: 'PowerShell',
  ps: 'PowerShell',
  ps1: 'PowerShell',
  prisma: 'Prisma',
  prolog: 'Prolog',
  proto: 'Protocol Buffer 3',
  protobuf: 'Protocol Buffer 3',
  pug: 'Pug',
  jade: 'Pug',
  puppet: 'Puppet',
  purescript: 'PureScript',
  python: 'Python',
  py: 'Python',
  qml: 'QML',
  qmldir: 'QML Directory',
  qss: 'Qt Style Sheets',
  r: 'R',
  racket: 'Racket',
  raku: 'Raku',
  perl6: 'Raku',
  razor: 'ASP.NET Razor',
  reg: 'Windows Registry Script',
  regexp: 'RegExp',
  regex: 'RegExp',
  rel: 'Rel',
  riscv: 'RISC-V',
  ron: 'RON',
  rosmsg: 'ROS Interface',
  rst: 'reStructuredText',
  ruby: 'Ruby',
  rb: 'Ruby',
  rust: 'Rust',
  rs: 'Rust',
  sas: 'SAS',
  sass: 'Sass',
  scala: 'Scala',
  scheme: 'Scheme',
  scss: 'SCSS',
  sdbl: '1C (Query)',
  '1c-query': '1C (Query)',
  shaderlab: 'ShaderLab',
  shader: 'ShaderLab',
  shellscript: 'Shell',
  bash: 'Shell',
  sh: 'Shell',
  shell: 'Shell',
  zsh: 'Shell',
  shellsession: 'Shell Session',
  console: 'Shell Session',
  smalltalk: 'Smalltalk',
  solidity: 'Solidity',
  soy: 'Closure Templates',
  'closure-templates': 'Closure Templates',
  sparql: 'SPARQL',
  splunk: 'Splunk Query Language',
  spl: 'Splunk Query Language',
  sql: 'SQL',
  'ssh-config': 'SSH Config',
  stata: 'Stata',
  stylus: 'Stylus',
  styl: 'Stylus',
  surrealql: 'SurrealQL',
  surql: 'SurrealQL',
  svelte: 'Svelte',
  swift: 'Swift',
  'system-verilog': 'SystemVerilog',
  systemd: 'Systemd Units',
  talonscript: 'TalonScript',
  talon: 'TalonScript',
  tasl: 'Tasl',
  tcl: 'Tcl',
  templ: 'Templ',
  terraform: 'Terraform',
  tf: 'Terraform',
  tfvars: 'Terraform',
  tex: 'TeX',
  toml: 'TOML',
  'ts-tags': 'TypeScript with Tags',
  lit: 'TypeScript with Tags',
  tsv: 'TSV',
  tsx: 'TSX',
  turtle: 'Turtle',
  twig: 'Twig',
  typescript: 'TypeScript',
  ts: 'TypeScript',
  cts: 'TypeScript',
  mts: 'TypeScript',
  typespec: 'TypeSpec',
  tsp: 'TypeSpec',
  typst: 'Typst',
  typ: 'Typst',
  v: 'V',
  vala: 'Vala',
  vb: 'Visual Basic',
  cmd: 'Visual Basic',
  verilog: 'Verilog',
  vhdl: 'VHDL',
  viml: 'Vim Script',
  vim: 'Vim Script',
  vimscript: 'Vim Script',
  vue: 'Vue',
  'vue-html': 'Vue HTML',
  'vue-vine': 'Vue Vine',
  vyper: 'Vyper',
  vy: 'Vyper',
  wasm: 'WebAssembly',
  wenyan: 'Wenyan',
  '文言': 'Wenyan',
  wgsl: 'WGSL',
  wikitext: 'Wikitext',
  mediawiki: 'Wikitext',
  wiki: 'Wikitext',
  wit: 'WebAssembly Interface Types',
  wolfram: 'Wolfram',
  wl: 'Wolfram',
  xml: 'XML',
  xsl: 'XSL',
  yaml: 'YAML',
  yml: 'YAML',
  zenscript: 'ZenScript',
  zig: 'Zig',
};
export function transformerAddLanguage(): ShikiTransformer {
  return {
    name: 'add-language-attribute',
    pre(node: Element) {
      const rawLang = this.options?.lang;
      if (rawLang && typeof rawLang === 'string') {
        const displayName = DISPLAY_NAMES[rawLang] || 
                            DISPLAY_NAMES[rawLang.toLowerCase()] ||
                            rawLang.charAt(0).toUpperCase() + rawLang.slice(1);
        
        node.properties = node.properties || {};
        node.properties['data-lang'] = rawLang;          // 👈 原始标识（用于下载）
        node.properties['data-language'] = displayName;  // 👈 友好名称（用于显示）
      }
    },
  };
}